### ISSUE TITLE
$this['grid'];

### ISSUE THREAD

**Issue by tivvit** [o5/grido-examples#24]
Hi,

what is this doing https://github.com/o5/grido-examples/blob/master/app/presenters/Presenter.php#L65 ?
I found that with editable grido (doctrine), everything works fine, but CMD+double click does nothing without that.

Thanks

**Comment by o5** [comment]
>  I found that with editable grido (doctrine), everything works fine, but CMD+double click does nothing without that.

Maybe, this https://github.com/o5/grido/issues/210 should be interested for you.
